"""
fix_llm_xml: Robust utility library to repair and parse malformed XML generated by Large Language Models (LLMs).

LLMs often produce XML with common errors: unescaped special characters, mismatched tags,
malformed CDATA sections, missing closing tags, etc. This library handles these edge cases
while preserving content integrity, designed specifically for LLM output scenarios.
"""
import re
from typing import Optional, Dict, List, Iterable, Tuple, Any, Set

import xmltodict
from lxml import etree

VERSION = '1.1'

# ------------------------------
# Constant Definitions
# ------------------------------
# Standard CDATA section markers
CDATA_START = '<![CDATA['
CDATA_END = ']]>'
# Escaped sequence for CDATA_END that can be safely embedded inside CDATA sections
ESCAPED_CDATA_END = ']]]]><![CDATA[>'

# Regex for valid XML tag names (supports namespace prefixes like `ns:tag`)
TAG_NAME_RE = re.compile(r'[a-zA-Z_:][\w:.-]*')
# Regex to detect malformed CDATA start patterns (e.g. <CDATA[, [{CDATA>, !CDATA> etc.)
CDATA_PREFIX_RE = re.compile(r'[<\[({!]+CDATA[\[({>]', re.IGNORECASE)
# Regex to detect valid XML entities (e.g. &lt;, &#160;, &#xA0;)
XML_ENTITY_RE = re.compile(r'&(?:[a-zA-Z0-9]+|#[0-9]{1,6}|#x[0-9a-fA-F]{1,6});')


# ------------------------------
# Public API Functions
# ------------------------------
def find_xml_document(s: str, root: str, with_tag: bool = False, cdata: bool = False) -> Optional[str]:
    """
    Extract content inside <{root}> tags from LLM-generated text, ignoring attributes and invalid formatting.

    This function is fault-tolerant and works even when the XML is partially malformed, or wrapped
    in extra non-XML text.

    Args:
        s: Input string containing (possibly malformed) XML
        root: Name of the target root tag to extract
        with_tag: If True, return the full content including the opening and closing <root> tags
        cdata: If True, expect content inside the root tag to be wrapped in <![CDATA[...]]>

    Returns:
        Extracted content string if tag is found, None otherwise. If closing tag is not found,
        returns all content after the opening tag.
    """
    start_pattern = rf'<{root}(\s+[^>]*)?>'
    if cdata:
        start_pattern += r'<!\[CDATA\['
    start_match = re.search(start_pattern, s, re.DOTALL)

    if not start_match:
        return None

    start_tag_end = start_match.end()
    start_pos = start_match.start() if with_tag else start_tag_end

    # Search for closing tag from end of string to handle nested tags with same name
    end_tag = f'</{root}>'
    if cdata:
        end_tag = CDATA_END + end_tag
    end_pos = s.rfind(end_tag)

    # If closing tag not found or appears before opening tag, return all content after opening tag
    if end_pos < start_tag_end:
        return s[start_pos:]

    if with_tag:
        end_pos += len(end_tag)
    return s[start_pos:end_pos]


def parse_xml(
    s: str, root: str,
    text_tags: Optional[List[str]] = None,
    **kwargs
) -> Optional[Dict]:
    """
    Parse LLM-generated XML string into a Python dictionary, with auto-repair for common errors.

    Will automatically attempt to fix malformed XML before parsing if initial parsing fails.

    Args:
        s: Input string containing XML
        root: Name of the expected root tag
        text_tags: List of known plain-text tags (tags that contain no child tags, only text content)
        **kwargs: Additional parameters passed to `xmltodict.parse`, common options:
            force_list (List[str]): Force specified tags to be parsed as lists even if only one instance exists
            strip_whitespace (bool): If True, strip leading/trailing whitespace from text values, default True

    Returns:
        Parsed dictionary on success, None if parsing fails even after repair attempts
    """
    xml_str = find_xml_document(s, root, with_tag=True)
    if not xml_str:
        return None

    text_tags_set = set(text_tags or [])
    try:
        parsed = xmltodict.parse(
            xml_str,
            process_namespaces=False,
            disable_entities=True,
            **kwargs
        )
    except Exception:
        # Attempt to repair XML before retry
        xml_str = fix_xml_with_text_tags(xml_str, text_tags_set)
        try:
            # Use lxml's recover mode to fix remaining structural errors
            root_elem = etree.fromstring(xml_str, parser=etree.XMLParser(
                recover=True, resolve_entities=False, no_network=True
            ))
            fixed_xml = etree.tostring(root_elem, encoding="unicode")
            return xmltodict.parse(
                fixed_xml,
                process_namespaces=False,
                disable_entities=True,
                **kwargs
            )
        except Exception:
            return None

    # Direct parsing succeeded; check if any text_tag still contains nested child elements
    if text_tags and _parsed_dict_has_nested_text_tags(parsed, text_tags_set):
        # Valid XML but text_tags have nested content
        try:
            fixed_xml = fix_xml_with_text_tags(xml_str, text_tags_set)
            return xmltodict.parse(
                fixed_xml,
                process_namespaces=False,
                disable_entities=True,
                **kwargs
            )
        except Exception:
            # Fallback: return original parsed result if flattening fails
            return parsed

    return parsed


def fix_xml_with_text_tags(xml: str, text_tags: Iterable[str] = ()) -> str:
    """
    Repair malformed XML, focusing on correct handling of plain text tags and content escaping.

    Handles the following common LLM XML errors:
    - Unescaped special characters (<, >, &) in plain text content
    - Malformed CDATA sections
    - Mismatched/extra closing tags
    - Missing closing tags for all elements
    - Invalid tag syntax

    Args:
        xml: Input malformed XML string
        text_tags: List of plain text tag names (case-sensitive, supports namespaces). These tags
            are expected to contain only text, no child elements, so any special characters inside
            will be properly escaped/wrapped in CDATA.

    Returns:
        Valid, well-formed XML string
    """
    text_tags_set = set(text_tags)
    output = []
    stack = []
    pos = 0
    n = len(xml)

    while pos < n:
        if xml[pos] == '<':
            parsed = _parse_xml_tag(xml, pos)
            if parsed is not None:
                tag_type, name, full_tag, start_pos, end_pos = parsed

                if tag_type in ('comment', 'self_close'):
                    output.append(full_tag)
                    pos = end_pos

                elif tag_type == 'start':
                    rest = xml[end_pos:]
                    if name in text_tags_set or CDATA_PREFIX_RE.match(rest):
                        # Process plain text tag with content repair
                        repaired, new_pos = _process_text_tag(
                            xml, end_pos, name, full_tag)
                        output.append(repaired)
                        pos = new_pos
                        # Do not push to stack, plain text tags have no children
                    else:
                        # Normal structural tag, push to stack
                        stack.append(name)
                        output.append(full_tag)
                        pos = end_pos

                elif tag_type == 'end':
                    # Only keep closing tag if matches stack top, discard mismatched ones
                    if stack and stack[-1] == name:
                        stack.pop()
                        output.append(full_tag)
                    pos = end_pos
            else:
                # Unrecognized tag syntax, treat '<' as normal text
                output.append('&lt;')
                pos += 1
        else:
            # Extract normal text block until next '<'
            next_lt = xml.find('<', pos)
            if next_lt == -1:
                text_block = xml[pos:]
                output.append(_escape_xml_entity(text_block))
                pos = n
            else:
                text_block = xml[pos:next_lt]
                output.append(_escape_xml_entity(text_block))
                pos = next_lt

    # Append missing closing tags for unclosed elements in stack
    for name in reversed(stack):
        output.append(f'</{name}>')

    return ''.join(output)


def get_xml_tag_text(value) -> str:
    """
    Extract text content from xmltodict parsing results, handling all edge value formats.

    Supported value types:
    - None / empty value → returns empty string
    - Plain string → returns the string directly
    - Dict with #text key (tag with attributes) → returns #text value
    - List of tags → takes first element and processes by above rules
    - Any other type → returns empty string

    Args:
        value: Value extracted from xmltodict parse result for a tag

    Returns:
        Clean text content string
    """
    if value is None:
        return ''
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        if not value:
            return ''
        return get_xml_tag_text(value[0])
    if isinstance(value, dict):
        return value.get('#text', '')
    return ''


# ------------------------------
# Internal Helper Functions
# ------------------------------
def _escape_cdata_ends(s: str) -> str:
    """
    Escape all bare CDATA_END (]]>) sequences in string to valid embedded format.
    Avoids double escaping existing properly escaped CDATA_END sequences.
    """
    parts = []
    i = 0
    n = len(s)
    while i < n:
        if s.startswith(ESCAPED_CDATA_END, i):
            parts.append(ESCAPED_CDATA_END)
            i += len(ESCAPED_CDATA_END)
        elif s.startswith(CDATA_END, i):
            parts.append(ESCAPED_CDATA_END)
            i += len(CDATA_END)
        else:
            j = i
            while j < n:
                if s.startswith(ESCAPED_CDATA_END, j) or s.startswith(CDATA_END, j):
                    break
                j += 1
            parts.append(s[i:j])
            i = j
    return ''.join(parts)


def _escape_xml_entity(s: str) -> str:
    """
    Escape special characters (<, >, &) in normal XML text content, preserving valid existing XML entities.
    """
    parts = []
    i = 0
    n = len(s)
    while i < n:
        next_pos_result = (
            s.find('<', i),
            s.find('>', i),
            s.find('&', i)
        )
        if next_pos_result == (-1, -1, -1):
            parts.append(s[i:])
            break
        next_pos = min(p for p in next_pos_result if p != -1)
        parts.append(s[i:next_pos])
        i = next_pos
        if s[i] == '<':
            parts.append('&lt;')
            i += 1
        elif s[i] == '>':
            parts.append('&gt;')
            i += 1
        else:
            entity_match = XML_ENTITY_RE.match(s, i)
            if entity_match:
                parts.append(entity_match.group())
                i = entity_match.end()
            else:
                parts.append('&amp;')
                i += 1
    return ''.join(parts)


def _parsed_dict_has_nested_text_tags(parsed: Dict[str, Any], text_tags_set: Set[str]) -> bool:
    """
    Recursively check if any tag in text_tags_set contains unexpected nested elements
    in the parsed dictionary (i.e. the xmltodict result has child keys other than
    attributes and #text for that tag).
    """
    def _value_has_children(value) -> bool:
        """Check if a parsed value represents an element with child elements (not just text)."""
        if isinstance(value, dict):
            for k in value:
                if not k.startswith('@') and k != '#text':
                    return True
        elif isinstance(value, list):
            for item in value:
                if _value_has_children(item):
                    return True
        return False

    def _check(obj) -> bool:
        if isinstance(obj, dict):
            for key, value in obj.items():
                if key in text_tags_set:
                    if _value_has_children(value):
                        return True
                else:
                    if _check(value):
                        return True
        elif isinstance(obj, list):
            for item in obj:
                if _check(item):
                    return True
        return False

    return _check(parsed)


def _parse_xml_tag(xml: str, pos: int) -> Optional[Tuple[str, Optional[str], str, int, int]]:
    """
    Try to parse an XML tag (comment, opening, closing, self-closing) from given position.

    Returns:
        Tuple (tag_type, name_or_None, full_tag_str, start_pos, end_pos) on success, None on failure.
        Tag types: 'comment', 'end' (closing tag), 'start' (opening tag), 'self_close' (self-closing tag)
    """
    if not xml:
        return None
    i = pos
    if xml[i] != '<':
        return None

    # 1. Comment tag: <!-- ... -->
    if xml.startswith('<!--', i):
        end = xml.find('-->', i + 4)
        if end == -1:
            end = len(xml) - 3
        else:
            end += 2
        full_tag = xml[i:end + 1]
        return ('comment', None, full_tag, i, end + 1)

    # 2. Closing tag: </name>
    if xml.startswith('</', i):
        j = xml.find('>', i + 2)
        if j == -1:
            return None
        inner = xml[i + 2:j].strip()
        match = TAG_NAME_RE.match(inner)
        if not match:
            return None
        name = match.group()
        full_tag = xml[i:j + 1]
        return ('end', name, full_tag, i, j + 1)

    # 3. Opening or self-closing tag: <name ...> / <name .../>
    j = i + 1
    match = TAG_NAME_RE.match(xml, j)
    if not match:
        return None
    name = match.group()
    j = match.end()

    # Scan attributes, skip '>' inside quoted attribute values
    in_single = False
    in_double = False
    while j < len(xml):
        c = xml[j]
        if in_single:
            if c == "'":
                in_single = False
        elif in_double:
            if c == '"':
                in_double = False
        elif c == "'":
            in_single = True
        elif c == '"':
            in_double = True
        elif c == '>':
            full_tag = xml[i:j + 1]
            if full_tag.endswith('/>'):
                return ('self_close', name, full_tag, i, j + 1)
            else:
                return ('start', name, full_tag, i, j + 1)
        j += 1

    # No closing '>' found for tag
    return None


def _process_text_tag(
    xml: str, content_start: int, tname: str,
    start_tag_str: str
) -> Tuple[str, int]:
    """
    Process a plain text tag: extract content, escape special characters/repair CDATA,
    return fully valid tag string and new parse position after the closing tag.
    """
    xml_len = len(xml)

    # Detect if content is wrapped in (possibly malformed) CDATA
    outer_is_cdata = False
    offset = 0
    rest = xml[content_start:]
    if rest.startswith(CDATA_START):
        outer_is_cdata = True
        offset = len(CDATA_START)
    else:
        m = CDATA_PREFIX_RE.match(rest)
        if m:
            outer_is_cdata = True
            offset = m.end()

    i = content_start + offset
    # Stack for nested content tracking: (type, is_cdata)
    stack = [('outer', outer_is_cdata)]

    content_end = xml_len
    outer_close_end = xml_len

    # Regex for malformed CDATA closing patterns
    compat_re = re.compile(r'(</CDATA>|\]+>+)</' + re.escape(tname) + '>') if outer_is_cdata else None
    close_tag = f'</{tname}>'
    close_combo = f']]></{tname}>'

    while i < xml_len:
        # Fast jump to only possible structural boundary characters
        if xml[i] not in '<]':
            next_items = (
                xml.find('<', i),
                xml.find(']', i),
            )
            candidates = [x for x in next_items if x != -1]
            if not candidates:
                break
            i = min(candidates)
            continue

        top_typ, top_is_cdata = stack[-1]

        # Handle ']' character sequences
        if xml[i] == ']':
            # Priority 1: Already escaped CDATA_END
            if (top_is_cdata or top_typ == 'cdata') and xml.startswith(ESCAPED_CDATA_END, i):
                i += len(ESCAPED_CDATA_END)
                continue

            # Priority 2: Valid CDATA closing + tag closing
            if top_is_cdata and top_typ in ('outer', 'inner'):
                if xml.startswith(close_combo, i):
                    if top_typ == 'outer':
                        content_end = i
                        outer_close_end = i + len(close_combo)
                        break
                    else:
                        stack.pop()
                        i += len(close_combo)
                        continue

            # Priority 3: Malformed CDATA closing pattern + tag closing (LLM common error)
            if top_typ == 'outer' and top_is_cdata and compat_re is not None:
                m = compat_re.match(xml, i)
                if m:
                    if m.group().endswith(close_combo):
                        content_end = m.end() - len(close_combo)
                    else:
                        content_end = m.start()
                    outer_close_end = m.end()
                    break

            # Priority 5: Normal CDATA section closing
            if top_typ == 'cdata' and xml.startswith(CDATA_END, i):
                stack.pop()
                i += len(CDATA_END)
                continue

            i += 1
            continue

        # Handle '<' character sequences
        if xml[i] == '<':
            # Priority 3: Malformed CDATA closing pattern + tag closing (LLM common error)
            if top_typ == 'outer' and top_is_cdata and compat_re is not None:
                m = compat_re.match(xml, i)
                if m:
                    if m.group().endswith(close_combo):
                        content_end = m.end() - len(close_combo)
                    else:
                        content_end = m.start()
                    outer_close_end = m.end()
                    break

            # Priority 4: Normal closing tag for current text tag
            if top_typ == 'outer' or (top_typ == 'inner' and not top_is_cdata):
                if xml.startswith(close_tag, i):
                    if top_typ == 'outer':
                        content_end = i
                        outer_close_end = i + len(close_tag)
                        # Fix inner `<![CDATA[` with outer `]]></tag>`
                        if top_is_cdata and i >= 3 and xml[i-3:i] == ']]>':
                            content_end -= 3
                        break
                    else:
                        stack.pop()
                        i += len(close_tag)
                        continue

            # Priority 6: Nested CDATA section start
            if top_is_cdata or top_typ == 'cdata':
                if xml.startswith(CDATA_START, i):
                    stack.append(('cdata', True))
                    i += len(CDATA_START)
                    continue

            # Priority 7: Nested same-name text tag start
            if xml.startswith(f'<{tname}', i):
                parsed = _parse_xml_tag(xml, i)
                if parsed and parsed[0] == 'start' and parsed[1] == tname:
                    _, _, full_tag, tag_start, tag_end = parsed
                    # Detect if inner tag content is CDATA
                    rest_after = xml[tag_end:]
                    inner_is_cdata = False
                    if rest_after.startswith(CDATA_START):
                        inner_is_cdata = True
                    else:
                        m_cdata = CDATA_PREFIX_RE.match(rest_after)
                        if m_cdata:
                            inner_is_cdata = True
                    stack.append(('inner', inner_is_cdata))
                    i = tag_end
                    continue

            # Unrecognized '<', treat as normal text
            i += 1
            continue

    # Fallback: search for closing tag from end if not found during forward scan
    if content_end == xml_len:
        search_start = content_start + offset
        best_pos = -1
        best_end = xml_len
        if outer_is_cdata:
            # First try to find valid CDATA + closing tag combo
            pos = xml.rfind(close_combo, search_start, xml_len)
            if pos != -1:
                best_pos = pos
                best_end = pos + len(close_combo)
            else:
                # Try malformed closing patterns
                if compat_re:
                    last_match = None
                    for m in compat_re.finditer(xml, search_start, xml_len):
                        last_match = m
                    if last_match:
                        best_pos = last_match.start()
                        best_end = last_match.end()
        # Finally try normal closing tag for all cases
        if best_pos == -1:
            pos = xml.rfind(close_tag, search_start, xml_len)
            if pos != -1:
                best_pos = pos
                best_end = pos + len(close_tag)

        if best_pos != -1:
            content_end = best_pos
            outer_close_end = best_end

    raw_content = xml[content_start + offset : content_end]

    # Repair content escaping
    if outer_is_cdata:
        if CDATA_END in raw_content:
            final_content = _escape_cdata_ends(raw_content)
        else:
            final_content = raw_content
        repaired = start_tag_str + CDATA_START + final_content + CDATA_END
    else:
        final_content = _escape_xml_entity(raw_content)
        repaired = start_tag_str + final_content

    # Ensure proper closing tag
    repaired += f'</{tname}>'

    return repaired, outer_close_end

